#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Replay YOLO probe JSONL into FlowSentry triage orchestrator (mock flow signals)"
    )
    parser.add_argument("probe_jsonl", help="Path to JSONL generated by run_flowsentry_yolo_probe.py")
    parser.add_argument(
        "--consistency-frames",
        type=int,
        default=3,
        help="Flow consistency frame threshold for triage replay",
    )
    parser.add_argument(
        "--iou-threshold",
        type=float,
        default=0.3,
        help="IoU threshold for person/flow matching in triage replay",
    )
    parser.add_argument(
        "--no-motion-reset-frames",
        type=int,
        default=5,
        help="FSM reset threshold when motion disappears",
    )
    parser.add_argument("--jsonl-out", help="Write per-frame triage replay records to JSONL")
    parser.add_argument("--summary-json", help="Write triage replay summary to JSON")
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Suppress per-frame stdout and print summary only",
    )
    args = parser.parse_args()

    from flowsentry.config import TriageConfig
    from flowsentry.runtime import (
        read_yolo_probe_jsonl,
        replay_yolo_probe_to_triage,
        summarize_triage_replay,
        write_triage_replay_jsonl,
        write_triage_replay_summary_json,
    )

    cfg = TriageConfig()
    cfg.flow.consistency_frames_threshold = args.consistency_frames
    cfg.fusion.iou_threshold = args.iou_threshold
    cfg.runtime.no_motion_reset_frames = args.no_motion_reset_frames

    probe_records = read_yolo_probe_jsonl(args.probe_jsonl)
    replay_records = replay_yolo_probe_to_triage(probe_records, triage_config=cfg)
    summary = summarize_triage_replay(replay_records)

    if args.jsonl_out:
        write_triage_replay_jsonl(replay_records, args.jsonl_out)
    if args.summary_json:
        write_triage_replay_summary_json(summary, args.summary_json)

    if not args.summary_only:
        for rec in replay_records:
            print(
                f"[frame={rec.frame_index} stream={rec.stream_id}] "
                f"state={rec.state} yolo={rec.yolo_enabled} "
                f"alarm={rec.alarm_triggered}:{rec.alarm_reason} "
                f"persons={rec.person_count} iou={rec.best_iou}"
            )

    print(
        "Summary: "
        f"frames={summary.frames_processed}, "
        f"alarms={summary.alarms_triggered}, "
        f"first_alarm_frame={summary.first_alarm_frame_index}, "
        f"alarm_reasons={summary.alarm_reasons}"
    )


if __name__ == "__main__":
    main()
